// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, project_id, key_hash, name)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, key_hash, name, created_at, last_used_at
`

type CreateAPIKeyParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	KeyHash   string `json:"key_hash"`
	Name      string `json:"name"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.ProjectID,
		arg.KeyHash,
		arg.Name,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.KeyHash,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one

INSERT INTO projects (id, name, slug, default_branch)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, default_branch, created_at
`

type CreateProjectParams struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Slug          string `json:"slug"`
	DefaultBranch string `json:"default_branch"`
}

// Projects & API keys (bootstrap/admin surface; dashboard endpoints get session auth in Phase 4).
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.DefaultBranch,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DefaultBranch,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, project_id FROM api_keys WHERE key_hash = $1
`

type GetAPIKeyByHashRow struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(&i.ID, &i.ProjectID)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, slug, default_branch, created_at FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DefaultBranch,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, name, slug, default_branch, created_at FROM projects WHERE slug = $1
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DefaultBranch,
		&i.CreatedAt,
	)
	return i, err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
