// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approval.sql

package db

import (
	"context"
)

const countRejectedSnapshots = `-- name: CountRejectedSnapshots :one
SELECT count(*) FROM snapshots WHERE build_id = $1 AND status = 'REJECTED'
`

// Rejected snapshots in a build (a single rejection moves the whole build to REJECTED).
func (q *Queries) CountRejectedSnapshots(ctx context.Context, buildID string) (int64, error) {
	row := q.db.QueryRow(ctx, countRejectedSnapshots, buildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBaselineForKey = `-- name: DeleteBaselineForKey :exec
DELETE FROM baselines
WHERE project_id = $1 AND branch = $2
  AND name = $3 AND browser = $4 AND viewport = $5
`

type DeleteBaselineForKeyParams struct {
	ProjectID string `json:"project_id"`
	Branch    string `json:"branch"`
	Name      string `json:"name"`
	Browser   string `json:"browser"`
	Viewport  string `json:"viewport"`
}

// Drop a baseline when an approved REMOVED snapshot accepts the deletion.
func (q *Queries) DeleteBaselineForKey(ctx context.Context, arg DeleteBaselineForKeyParams) error {
	_, err := q.db.Exec(ctx, deleteBaselineForKey,
		arg.ProjectID,
		arg.Branch,
		arg.Name,
		arg.Browser,
		arg.Viewport,
	)
	return err
}

const getProjectGitlab = `-- name: GetProjectGitlab :one
SELECT id, name, slug, gitlab_project_id FROM projects WHERE id = $1
`

type GetProjectGitlabRow struct {
	ID              string  `json:"id"`
	Name            string  `json:"name"`
	Slug            string  `json:"slug"`
	GitlabProjectID *string `json:"gitlab_project_id"`
}

// Project's GitLab wiring (used by the git-sync worker to commit baselines / post MR status).
func (q *Queries) GetProjectGitlab(ctx context.Context, id string) (GetProjectGitlabRow, error) {
	row := q.db.QueryRow(ctx, getProjectGitlab, id)
	var i GetProjectGitlabRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.GitlabProjectID,
	)
	return i, err
}

const getSnapshotForReview = `-- name: GetSnapshotForReview :one

SELECT
  s.id, s.build_id, b.project_id, b.branch,
  s.name, s.browser, s.viewport, s.new_image_sha, s.baseline_path, s.status
FROM snapshots s
JOIN builds b ON b.id = s.build_id
JOIN memberships m ON m.project_id = b.project_id
WHERE s.id = $1 AND m.user_id = $2
`

type GetSnapshotForReviewParams struct {
	SnapshotID string `json:"snapshot_id"`
	UserID     string `json:"user_id"`
}

type GetSnapshotForReviewRow struct {
	ID           string         `json:"id"`
	BuildID      string         `json:"build_id"`
	ProjectID    string         `json:"project_id"`
	Branch       string         `json:"branch"`
	Name         string         `json:"name"`
	Browser      string         `json:"browser"`
	Viewport     string         `json:"viewport"`
	NewImageSha  *string        `json:"new_image_sha"`
	BaselinePath *string        `json:"baseline_path"`
	Status       SnapshotStatus `json:"status"`
}

// Approval workflow (Phase 5): approve/reject snapshots, move the git-native baseline (Mode A), and
// recompute the build's aggregate status. Approve of a CHANGED/NEW snapshot promotes its new image to
// the (project, branch, name, browser, viewport) baseline; approve of a REMOVED snapshot accepts the
// deletion and drops the baseline; reject marks the snapshot REJECTED. Membership is enforced by the
// join (a non-member resolves to no row → 403/404 at the handler).
func (q *Queries) GetSnapshotForReview(ctx context.Context, arg GetSnapshotForReviewParams) (GetSnapshotForReviewRow, error) {
	row := q.db.QueryRow(ctx, getSnapshotForReview, arg.SnapshotID, arg.UserID)
	var i GetSnapshotForReviewRow
	err := row.Scan(
		&i.ID,
		&i.BuildID,
		&i.ProjectID,
		&i.Branch,
		&i.Name,
		&i.Browser,
		&i.Viewport,
		&i.NewImageSha,
		&i.BaselinePath,
		&i.Status,
	)
	return i, err
}

const insertApprovalEvent = `-- name: InsertApprovalEvent :exec
INSERT INTO approval_events (id, snapshot_id, user_id, action)
VALUES ($1, $2, $3, $4)
`

type InsertApprovalEventParams struct {
	ID         string         `json:"id"`
	SnapshotID string         `json:"snapshot_id"`
	UserID     string         `json:"user_id"`
	Action     ApprovalAction `json:"action"`
}

func (q *Queries) InsertApprovalEvent(ctx context.Context, arg InsertApprovalEventParams) error {
	_, err := q.db.Exec(ctx, insertApprovalEvent,
		arg.ID,
		arg.SnapshotID,
		arg.UserID,
		arg.Action,
	)
	return err
}

const listReviewableSnapshotsForBuild = `-- name: ListReviewableSnapshotsForBuild :many
SELECT s.id, s.name, s.browser, s.viewport, s.new_image_sha, s.baseline_path, s.status, b.project_id, b.branch
FROM snapshots s
JOIN builds b ON b.id = s.build_id
WHERE s.build_id = $1 AND s.status IN ('CHANGED', 'NEW', 'REMOVED', 'ERROR')
ORDER BY s.name, s.browser, s.viewport
`

type ListReviewableSnapshotsForBuildRow struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Browser      string         `json:"browser"`
	Viewport     string         `json:"viewport"`
	NewImageSha  *string        `json:"new_image_sha"`
	BaselinePath *string        `json:"baseline_path"`
	Status       SnapshotStatus `json:"status"`
	ProjectID    string         `json:"project_id"`
	Branch       string         `json:"branch"`
}

// All snapshots in a build that a reviewer can act on (batch approve/reject). Build membership is
// checked separately via GetBuildForMember before this runs.
func (q *Queries) ListReviewableSnapshotsForBuild(ctx context.Context, buildID string) ([]ListReviewableSnapshotsForBuildRow, error) {
	rows, err := q.db.Query(ctx, listReviewableSnapshotsForBuild, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewableSnapshotsForBuildRow
	for rows.Next() {
		var i ListReviewableSnapshotsForBuildRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Browser,
			&i.Viewport,
			&i.NewImageSha,
			&i.BaselinePath,
			&i.Status,
			&i.ProjectID,
			&i.Branch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectGitlab = `-- name: SetProjectGitlab :exec
UPDATE projects SET gitlab_project_id = $1 WHERE slug = $2
`

type SetProjectGitlabParams struct {
	GitlabProjectID *string `json:"gitlab_project_id"`
	Slug            string  `json:"slug"`
}

// Set (or clear) a project's GitLab repo id/path (admin CLI: `pixela project set-gitlab`).
func (q *Queries) SetProjectGitlab(ctx context.Context, arg SetProjectGitlabParams) error {
	_, err := q.db.Exec(ctx, setProjectGitlab, arg.GitlabProjectID, arg.Slug)
	return err
}

const setSnapshotApproved = `-- name: SetSnapshotApproved :exec
UPDATE snapshots SET status = 'APPROVED' WHERE id = $1
`

func (q *Queries) SetSnapshotApproved(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setSnapshotApproved, id)
	return err
}

const setSnapshotRejected = `-- name: SetSnapshotRejected :exec
UPDATE snapshots SET status = 'REJECTED' WHERE id = $1
`

func (q *Queries) SetSnapshotRejected(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setSnapshotRejected, id)
	return err
}

const upsertBaseline = `-- name: UpsertBaseline :exec
INSERT INTO baselines (id, project_id, branch, name, browser, viewport, image_sha, approved_by_user_id, approved_in_build_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (project_id, branch, name, browser, viewport)
DO UPDATE SET
  image_sha = EXCLUDED.image_sha,
  approved_by_user_id = EXCLUDED.approved_by_user_id,
  approved_in_build_id = EXCLUDED.approved_in_build_id,
  updated_at = now()
`

type UpsertBaselineParams struct {
	ID                string  `json:"id"`
	ProjectID         string  `json:"project_id"`
	Branch            string  `json:"branch"`
	Name              string  `json:"name"`
	Browser           string  `json:"browser"`
	Viewport          string  `json:"viewport"`
	ImageSha          string  `json:"image_sha"`
	ApprovedByUserID  *string `json:"approved_by_user_id"`
	ApprovedInBuildID *string `json:"approved_in_build_id"`
}

// Promote (or move) the baseline for a snapshot's identity key. The unique key makes this an upsert,
// so re-approving the same key just advances image_sha + provenance.
func (q *Queries) UpsertBaseline(ctx context.Context, arg UpsertBaselineParams) error {
	_, err := q.db.Exec(ctx, upsertBaseline,
		arg.ID,
		arg.ProjectID,
		arg.Branch,
		arg.Name,
		arg.Browser,
		arg.Viewport,
		arg.ImageSha,
		arg.ApprovedByUserID,
		arg.ApprovedInBuildID,
	)
	return err
}
