// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBuildsForProjectMember = `-- name: CountBuildsForProjectMember :one
SELECT count(*)
FROM builds b
WHERE b.project_id = $1
  AND EXISTS (SELECT 1 FROM memberships m WHERE m.user_id = $2 AND m.project_id = b.project_id)
  AND ($3::text = '' OR b.branch = $3)
  AND ($4::text = '' OR b.status::text = $4)
`

type CountBuildsForProjectMemberParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
	Branch    string `json:"branch"`
	Status    string `json:"status"`
}

// Total matching builds (for totalPages). Mirrors the filters/membership of the feed query.
func (q *Queries) CountBuildsForProjectMember(ctx context.Context, arg CountBuildsForProjectMemberParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBuildsForProjectMember,
		arg.ProjectID,
		arg.UserID,
		arg.Branch,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (id, user_id, project_id, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, project_id) DO UPDATE SET role = EXCLUDED.role
RETURNING id, user_id, project_id, role
`

type CreateMembershipParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
	Role      Role   `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.Role,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Role,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, email, name, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, password_hash, gitlab_id, created_at
`

type CreateUserParams struct {
	ID           string  `json:"id"`
	Email        string  `json:"email"`
	Name         *string `json:"name"`
	PasswordHash *string `json:"password_hash"`
}

// Dashboard reads + user/membership management (Phase 4). All multi-project reads are scoped at the
// query level to the requesting user's memberships (spec §10 F-36: WHERE project_id IN user's projects),
// never by post-filtering in Go.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.GitlabID,
		&i.CreatedAt,
	)
	return i, err
}

const getBuildForMember = `-- name: GetBuildForMember :one
SELECT b.id, b.project_id, b.branch, b.commit_sha, b.status, b.created_at, b.finalized_at, b.ci_job_url
FROM builds b
JOIN memberships m ON m.project_id = b.project_id
WHERE b.id = $1 AND m.user_id = $2
`

type GetBuildForMemberParams struct {
	BuildID string `json:"build_id"`
	UserID  string `json:"user_id"`
}

type GetBuildForMemberRow struct {
	ID          string             `json:"id"`
	ProjectID   string             `json:"project_id"`
	Branch      string             `json:"branch"`
	CommitSha   string             `json:"commit_sha"`
	Status      BuildStatus        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	FinalizedAt pgtype.Timestamptz `json:"finalized_at"`
	CiJobUrl    *string            `json:"ci_job_url"`
}

// A build the user may see (membership-scoped join). No row ⇒ not found OR not a member: the handler
// distinguishes 404 vs 403 by also checking build existence/ownership.
func (q *Queries) GetBuildForMember(ctx context.Context, arg GetBuildForMemberParams) (GetBuildForMemberRow, error) {
	row := q.db.QueryRow(ctx, getBuildForMember, arg.BuildID, arg.UserID)
	var i GetBuildForMemberRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Branch,
		&i.CommitSha,
		&i.Status,
		&i.CreatedAt,
		&i.FinalizedAt,
		&i.CiJobUrl,
	)
	return i, err
}

const getBuildProject = `-- name: GetBuildProject :one
SELECT b.project_id FROM builds b WHERE b.id = $1
`

// The owning project of a build, regardless of membership — used to return a precise 403 (vs 404).
func (q *Queries) GetBuildProject(ctx context.Context, buildID string) (string, error) {
	row := q.db.QueryRow(ctx, getBuildProject, buildID)
	var project_id string
	err := row.Scan(&project_id)
	return project_id, err
}

const getSnapshotForMember = `-- name: GetSnapshotForMember :one
SELECT
  s.id, s.name, s.browser, s.viewport, s.status, s.diff_ratio, s.diff_pixels,
  s.new_image_sha, s.diff_image_sha, s.baseline_id,
  bl.image_sha AS baseline_image_sha,
  b.project_id
FROM snapshots s
JOIN builds b ON b.id = s.build_id
JOIN memberships m ON m.project_id = b.project_id
LEFT JOIN baselines bl ON bl.id = s.baseline_id
WHERE s.id = $1 AND m.user_id = $2
`

type GetSnapshotForMemberParams struct {
	SnapshotID string `json:"snapshot_id"`
	UserID     string `json:"user_id"`
}

type GetSnapshotForMemberRow struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	Browser          string         `json:"browser"`
	Viewport         string         `json:"viewport"`
	Status           SnapshotStatus `json:"status"`
	DiffRatio        *float64       `json:"diff_ratio"`
	DiffPixels       *int32         `json:"diff_pixels"`
	NewImageSha      *string        `json:"new_image_sha"`
	DiffImageSha     *string        `json:"diff_image_sha"`
	BaselineID       *string        `json:"baseline_id"`
	BaselineImageSha *string        `json:"baseline_image_sha"`
	ProjectID        string         `json:"project_id"`
}

// A snapshot the user may see, with everything needed for the review view, scoped by membership.
func (q *Queries) GetSnapshotForMember(ctx context.Context, arg GetSnapshotForMemberParams) (GetSnapshotForMemberRow, error) {
	row := q.db.QueryRow(ctx, getSnapshotForMember, arg.SnapshotID, arg.UserID)
	var i GetSnapshotForMemberRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Browser,
		&i.Viewport,
		&i.Status,
		&i.DiffRatio,
		&i.DiffPixels,
		&i.NewImageSha,
		&i.DiffImageSha,
		&i.BaselineID,
		&i.BaselineImageSha,
		&i.ProjectID,
	)
	return i, err
}

const getSnapshotProject = `-- name: GetSnapshotProject :one
SELECT b.project_id
FROM snapshots s
JOIN builds b ON b.id = s.build_id
WHERE s.id = $1
`

// The owning project of a snapshot, regardless of membership — used for a precise 403 (vs 404).
func (q *Queries) GetSnapshotProject(ctx context.Context, snapshotID string) (string, error) {
	row := q.db.QueryRow(ctx, getSnapshotProject, snapshotID)
	var project_id string
	err := row.Scan(&project_id)
	return project_id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, gitlab_id, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.GitlabID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID    string  `json:"id"`
	Email string  `json:"email"`
	Name  *string `json:"name"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.ID, &i.Email, &i.Name)
	return i, err
}

const isProjectMember = `-- name: IsProjectMember :one
SELECT EXISTS (
  SELECT 1 FROM memberships WHERE user_id = $1 AND project_id = $2
) AS is_member
`

type IsProjectMemberParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

// Membership guard: is the user a member of this project? (used by per-resource 403 checks).
func (q *Queries) IsProjectMember(ctx context.Context, arg IsProjectMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isProjectMember, arg.UserID, arg.ProjectID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listActivityForUser = `-- name: ListActivityForUser :many
SELECT
  ae.id, ae.action, ae.created_at,
  u.email      AS user_email,
  s.id         AS snapshot_id,
  s.name       AS snapshot_name,
  b.branch     AS branch,
  p.id         AS project_id,
  p.name       AS project_name
FROM approval_events ae
JOIN users u ON u.id = ae.user_id
JOIN snapshots s ON s.id = ae.snapshot_id
JOIN builds b ON b.id = s.build_id
JOIN projects p ON p.id = b.project_id
WHERE EXISTS (SELECT 1 FROM memberships m WHERE m.user_id = $1 AND m.project_id = p.id)
ORDER BY ae.created_at DESC
LIMIT $2
`

type ListActivityForUserParams struct {
	UserID    string `json:"user_id"`
	PageLimit int32  `json:"page_limit"`
}

type ListActivityForUserRow struct {
	ID           string             `json:"id"`
	Action       ApprovalAction     `json:"action"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UserEmail    string             `json:"user_email"`
	SnapshotID   string             `json:"snapshot_id"`
	SnapshotName string             `json:"snapshot_name"`
	Branch       string             `json:"branch"`
	ProjectID    string             `json:"project_id"`
	ProjectName  string             `json:"project_name"`
}

// Organization activity feed: approval events across every project the user is a member of, newest
// first. The membership EXISTS predicate keeps the feed scoped — a user never sees another org's events.
func (q *Queries) ListActivityForUser(ctx context.Context, arg ListActivityForUserParams) ([]ListActivityForUserRow, error) {
	rows, err := q.db.Query(ctx, listActivityForUser, arg.UserID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivityForUserRow
	for rows.Next() {
		var i ListActivityForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.CreatedAt,
			&i.UserEmail,
			&i.SnapshotID,
			&i.SnapshotName,
			&i.Branch,
			&i.ProjectID,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalEvents = `-- name: ListApprovalEvents :many
SELECT ae.action, u.email AS user_email, ae.created_at
FROM approval_events ae
JOIN users u ON u.id = ae.user_id
WHERE ae.snapshot_id = $1
ORDER BY ae.created_at DESC
`

type ListApprovalEventsRow struct {
	Action    ApprovalAction     `json:"action"`
	UserEmail string             `json:"user_email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Approval history feed for a snapshot (audit, spec §10): action / who / when.
func (q *Queries) ListApprovalEvents(ctx context.Context, snapshotID string) ([]ListApprovalEventsRow, error) {
	rows, err := q.db.Query(ctx, listApprovalEvents, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApprovalEventsRow
	for rows.Next() {
		var i ListApprovalEventsRow
		if err := rows.Scan(&i.Action, &i.UserEmail, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildsForProjectMember = `-- name: ListBuildsForProjectMember :many
SELECT
  b.id, b.branch, b.commit_sha, b.status, b.created_at, b.finalized_at, b.ci_job_url,
  count(s.id) FILTER (WHERE s.status = 'UNCHANGED') AS unchanged,
  count(s.id) FILTER (WHERE s.status = 'CHANGED')   AS changed,
  count(s.id) FILTER (WHERE s.status = 'NEW')       AS new,
  count(s.id) FILTER (WHERE s.status = 'REMOVED')   AS removed
FROM builds b
LEFT JOIN snapshots s ON s.build_id = b.id
WHERE b.project_id = $1
  AND EXISTS (SELECT 1 FROM memberships m WHERE m.user_id = $2 AND m.project_id = b.project_id)
  AND ($3::text = '' OR b.branch = $3)
  AND ($4::text = '' OR b.status::text = $4)
GROUP BY b.id
ORDER BY b.created_at DESC
LIMIT $6 OFFSET $5
`

type ListBuildsForProjectMemberParams struct {
	ProjectID  string `json:"project_id"`
	UserID     string `json:"user_id"`
	Branch     string `json:"branch"`
	Status     string `json:"status"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type ListBuildsForProjectMemberRow struct {
	ID          string             `json:"id"`
	Branch      string             `json:"branch"`
	CommitSha   string             `json:"commit_sha"`
	Status      BuildStatus        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	FinalizedAt pgtype.Timestamptz `json:"finalized_at"`
	CiJobUrl    *string            `json:"ci_job_url"`
	Unchanged   int64              `json:"unchanged"`
	Changed     int64              `json:"changed"`
	New         int64              `json:"new"`
	Removed     int64              `json:"removed"`
}

// Builds feed for a project the user can see, with per-status snapshot counts computed in SQL
// (count(*) FILTER), filtered by optional branch/status, paginated. The membership predicate is part of
// the query so a non-member can never read another project's builds.
func (q *Queries) ListBuildsForProjectMember(ctx context.Context, arg ListBuildsForProjectMemberParams) ([]ListBuildsForProjectMemberRow, error) {
	rows, err := q.db.Query(ctx, listBuildsForProjectMember,
		arg.ProjectID,
		arg.UserID,
		arg.Branch,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBuildsForProjectMemberRow
	for rows.Next() {
		var i ListBuildsForProjectMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.Branch,
			&i.CommitSha,
			&i.Status,
			&i.CreatedAt,
			&i.FinalizedAt,
			&i.CiJobUrl,
			&i.Unchanged,
			&i.Changed,
			&i.New,
			&i.Removed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectBaselines = `-- name: ListProjectBaselines :many
SELECT
  bl.id, bl.branch, bl.name, bl.browser, bl.viewport, bl.image_sha,
  bl.updated_at, bl.created_at,
  u.email AS approved_by_email
FROM baselines bl
LEFT JOIN users u ON u.id = bl.approved_by_user_id
WHERE bl.project_id = $1
ORDER BY bl.branch, bl.name, bl.browser, bl.viewport
`

type ListProjectBaselinesRow struct {
	ID              string             `json:"id"`
	Branch          string             `json:"branch"`
	Name            string             `json:"name"`
	Browser         string             `json:"browser"`
	Viewport        string             `json:"viewport"`
	ImageSha        string             `json:"image_sha"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ApprovedByEmail *string            `json:"approved_by_email"`
}

// Per-branch baselines of a project (Базовые линии screen): the canonical accepted snapshot for each
// (branch, name, browser, viewport), with the blob sha (presigned by the service), who accepted it, and
// when it was last updated. Membership is enforced at the handler.
func (q *Queries) ListProjectBaselines(ctx context.Context, projectID string) ([]ListProjectBaselinesRow, error) {
	rows, err := q.db.Query(ctx, listProjectBaselines, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectBaselinesRow
	for rows.Next() {
		var i ListProjectBaselinesRow
		if err := rows.Scan(
			&i.ID,
			&i.Branch,
			&i.Name,
			&i.Browser,
			&i.Viewport,
			&i.ImageSha,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.ApprovedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT
  u.id, u.email, u.name, m.role,
  (SELECT count(*) FROM approval_events ae WHERE ae.user_id = u.id) AS total_reviews
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.project_id = $1
ORDER BY m.role, u.email
`

type ListProjectMembersRow struct {
	ID           string  `json:"id"`
	Email        string  `json:"email"`
	Name         *string `json:"name"`
	Role         Role    `json:"role"`
	TotalReviews int64   `json:"total_reviews"`
}

// Members of a project (membership-scoped at the handler): each member's identity, role, and a real
// all-time review tally (approval events authored). Used by the Участники screen.
func (q *Queries) ListProjectMembers(ctx context.Context, projectID string) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMembersRow
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.TotalReviews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT p.id, p.name, p.slug, p.default_branch, p.created_at, m.role
FROM projects p
JOIN memberships m ON m.project_id = p.id
WHERE m.user_id = $1
ORDER BY p.created_at DESC
`

type ListProjectsForUserRow struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	DefaultBranch string             `json:"default_branch"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Role          Role               `json:"role"`
}

// Projects the user belongs to (membership-scoped list).
func (q *Queries) ListProjectsForUser(ctx context.Context, userID string) ([]ListProjectsForUserRow, error) {
	rows, err := q.db.Query(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsForUserRow
	for rows.Next() {
		var i ListProjectsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.DefaultBranch,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsOverview = `-- name: ListProjectsOverview :many
SELECT
  p.id, p.name, p.slug, p.default_branch, p.created_at, m.role,
  (SELECT count(*) FROM builds b WHERE b.project_id = p.id AND b.status = 'REVIEW_REQUIRED') AS open_reviews,
  (SELECT count(*) FROM memberships mm WHERE mm.project_id = p.id) AS member_count,
  lb.created_at AS last_build_at,
  lb.status     AS last_build_status,
  coalesce(lc.ok, 0)    AS health_ok,
  coalesce(lc.total, 0) AS health_total
FROM projects p
JOIN memberships m ON m.project_id = p.id
LEFT JOIN LATERAL (
  SELECT b.id, b.created_at, b.status
  FROM builds b WHERE b.project_id = p.id
  ORDER BY b.created_at DESC LIMIT 1
) lb ON true
LEFT JOIN LATERAL (
  SELECT
    count(*) FILTER (WHERE s.status IN ('UNCHANGED', 'APPROVED')) AS ok,
    count(*) AS total
  FROM snapshots s WHERE s.build_id = lb.id
) lc ON true
WHERE m.user_id = $1
ORDER BY p.created_at DESC
`

type ListProjectsOverviewRow struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	DefaultBranch   string             `json:"default_branch"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Role            Role               `json:"role"`
	OpenReviews     int64              `json:"open_reviews"`
	MemberCount     int64              `json:"member_count"`
	LastBuildAt     pgtype.Timestamptz `json:"last_build_at"`
	LastBuildStatus BuildStatus        `json:"last_build_status"`
	HealthOk        int64              `json:"health_ok"`
	HealthTotal     int64              `json:"health_total"`
}

// Membership-scoped project overview: each project the user belongs to, enriched with real aggregates
// computed in SQL — open reviews (builds awaiting review), member count, last build time, and the latest
// build's "in-norm" snapshot ratio (UNCHANGED+APPROVED over total) for the health bar. Every figure is
// derived from existing rows; nothing is synthesised.
func (q *Queries) ListProjectsOverview(ctx context.Context, userID string) ([]ListProjectsOverviewRow, error) {
	rows, err := q.db.Query(ctx, listProjectsOverview, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsOverviewRow
	for rows.Next() {
		var i ListProjectsOverviewRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.DefaultBranch,
			&i.CreatedAt,
			&i.Role,
			&i.OpenReviews,
			&i.MemberCount,
			&i.LastBuildAt,
			&i.LastBuildStatus,
			&i.HealthOk,
			&i.HealthTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsForBuild = `-- name: ListSnapshotsForBuild :many
SELECT s.id, s.name, s.browser, s.viewport, s.status, s.diff_ratio,
       s.new_image_sha, s.diff_image_sha, bl.image_sha AS baseline_image_sha
FROM snapshots s
LEFT JOIN baselines bl ON bl.id = s.baseline_id
WHERE s.build_id = $1
ORDER BY s.name, s.browser, s.viewport
`

type ListSnapshotsForBuildRow struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	Browser          string         `json:"browser"`
	Viewport         string         `json:"viewport"`
	Status           SnapshotStatus `json:"status"`
	DiffRatio        *float64       `json:"diff_ratio"`
	NewImageSha      *string        `json:"new_image_sha"`
	DiffImageSha     *string        `json:"diff_image_sha"`
	BaselineImageSha *string        `json:"baseline_image_sha"`
}

// Snapshots of a build (brief metadata + image shas for the build-detail thumbnail grid). The new and
// diff blobs are the snapshot's own; the baseline blob is resolved through baseline_id. The service
// presigns whichever are non-null so the grid can render a real thumbnail per card.
func (q *Queries) ListSnapshotsForBuild(ctx context.Context, buildID string) ([]ListSnapshotsForBuildRow, error) {
	rows, err := q.db.Query(ctx, listSnapshotsForBuild, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSnapshotsForBuildRow
	for rows.Next() {
		var i ListSnapshotsForBuildRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Browser,
			&i.Viewport,
			&i.Status,
			&i.DiffRatio,
			&i.NewImageSha,
			&i.DiffImageSha,
			&i.BaselineImageSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
