// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diff.sql

package db

import (
	"context"
)

const countPendingSnapshots = `-- name: CountPendingSnapshots :one
SELECT count(*) FROM snapshots WHERE build_id = $1 AND status = 'PENDING'
`

func (q *Queries) CountPendingSnapshots(ctx context.Context, buildID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingSnapshots, buildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviewableSnapshots = `-- name: CountReviewableSnapshots :one
SELECT count(*) FROM snapshots
WHERE build_id = $1 AND status IN ('CHANGED', 'NEW', 'REMOVED', 'ERROR')
`

// Reviewable = anything that blocks a clean pass (CHANGED/NEW/REMOVED/ERROR). Approved changes count
// as resolved, so they do NOT block PASSED.
func (q *Queries) CountReviewableSnapshots(ctx context.Context, buildID string) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewableSnapshots, buildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBaselineForKey = `-- name: GetBaselineForKey :one
SELECT id, project_id, branch, name, browser, viewport, image_sha, approved_by_user_id, approved_in_build_id, updated_at, created_at FROM baselines
WHERE project_id = $1 AND branch = $2
  AND name = $3 AND browser = $4 AND viewport = $5
`

type GetBaselineForKeyParams struct {
	ProjectID string `json:"project_id"`
	Branch    string `json:"branch"`
	Name      string `json:"name"`
	Browser   string `json:"browser"`
	Viewport  string `json:"viewport"`
}

// Baseline resolution: strictly within the branch (NO merge-base; invariant #1).
func (q *Queries) GetBaselineForKey(ctx context.Context, arg GetBaselineForKeyParams) (Baseline, error) {
	row := q.db.QueryRow(ctx, getBaselineForKey,
		arg.ProjectID,
		arg.Branch,
		arg.Name,
		arg.Browser,
		arg.Viewport,
	)
	var i Baseline
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Branch,
		&i.Name,
		&i.Browser,
		&i.Viewport,
		&i.ImageSha,
		&i.ApprovedByUserID,
		&i.ApprovedInBuildID,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSnapshot = `-- name: GetSnapshot :one

SELECT id, build_id, name, browser, viewport, new_image_sha, diff_image_sha, baseline_id, diff_ratio, diff_pixels, status, error_msg, created_at FROM snapshots WHERE id = $1
`

// Diff pipeline (Phase 2): baseline resolution, per-snapshot result, build-status recompute.
func (q *Queries) GetSnapshot(ctx context.Context, id string) (Snapshot, error) {
	row := q.db.QueryRow(ctx, getSnapshot, id)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.BuildID,
		&i.Name,
		&i.Browser,
		&i.Viewport,
		&i.NewImageSha,
		&i.DiffImageSha,
		&i.BaselineID,
		&i.DiffRatio,
		&i.DiffPixels,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
	)
	return i, err
}

const setBuildStatus = `-- name: SetBuildStatus :exec
UPDATE builds SET status = $1 WHERE id = $2
`

type SetBuildStatusParams struct {
	Status BuildStatus `json:"status"`
	ID     string      `json:"id"`
}

func (q *Queries) SetBuildStatus(ctx context.Context, arg SetBuildStatusParams) error {
	_, err := q.db.Exec(ctx, setBuildStatus, arg.Status, arg.ID)
	return err
}

const setSnapshotChanged = `-- name: SetSnapshotChanged :exec
UPDATE snapshots
SET status = 'CHANGED', diff_ratio = $1, diff_pixels = $2,
    diff_image_sha = $3, baseline_id = $4
WHERE id = $5
`

type SetSnapshotChangedParams struct {
	DiffRatio    *float64 `json:"diff_ratio"`
	DiffPixels   *int32   `json:"diff_pixels"`
	DiffImageSha *string  `json:"diff_image_sha"`
	BaselineID   *string  `json:"baseline_id"`
	ID           string   `json:"id"`
}

func (q *Queries) SetSnapshotChanged(ctx context.Context, arg SetSnapshotChangedParams) error {
	_, err := q.db.Exec(ctx, setSnapshotChanged,
		arg.DiffRatio,
		arg.DiffPixels,
		arg.DiffImageSha,
		arg.BaselineID,
		arg.ID,
	)
	return err
}

const setSnapshotError = `-- name: SetSnapshotError :exec
UPDATE snapshots SET status = 'ERROR', error_msg = $1 WHERE id = $2
`

type SetSnapshotErrorParams struct {
	ErrorMsg *string `json:"error_msg"`
	ID       string  `json:"id"`
}

func (q *Queries) SetSnapshotError(ctx context.Context, arg SetSnapshotErrorParams) error {
	_, err := q.db.Exec(ctx, setSnapshotError, arg.ErrorMsg, arg.ID)
	return err
}

const setSnapshotNew = `-- name: SetSnapshotNew :exec
UPDATE snapshots
SET status = 'NEW', diff_ratio = NULL, diff_pixels = NULL, diff_image_sha = NULL
WHERE id = $1
`

func (q *Queries) SetSnapshotNew(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setSnapshotNew, id)
	return err
}

const setSnapshotUnchanged = `-- name: SetSnapshotUnchanged :exec
UPDATE snapshots
SET status = 'UNCHANGED', diff_ratio = 0, diff_pixels = 0, diff_image_sha = NULL, baseline_id = $1
WHERE id = $2
`

type SetSnapshotUnchangedParams struct {
	BaselineID *string `json:"baseline_id"`
	ID         string  `json:"id"`
}

func (q *Queries) SetSnapshotUnchanged(ctx context.Context, arg SetSnapshotUnchangedParams) error {
	_, err := q.db.Exec(ctx, setSnapshotUnchanged, arg.BaselineID, arg.ID)
	return err
}
