// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingestion.sql

package db

import (
	"context"
)

const createBuild = `-- name: CreateBuild :one

INSERT INTO builds (id, project_id, branch, commit_sha, ci_build_id, ci_job_url, mr_iid, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'RUNNING')
RETURNING id, project_id, branch, commit_sha, ci_build_id, ci_job_url, mr_iid, status, created_at, finalized_at
`

type CreateBuildParams struct {
	ID        string  `json:"id"`
	ProjectID string  `json:"project_id"`
	Branch    string  `json:"branch"`
	CommitSha string  `json:"commit_sha"`
	CiBuildID *string `json:"ci_build_id"`
	CiJobUrl  *string `json:"ci_job_url"`
	MrIid     *string `json:"mr_iid"`
}

// Ingestion: builds, snapshots, images, baselines (Phase 1).
func (q *Queries) CreateBuild(ctx context.Context, arg CreateBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, createBuild,
		arg.ID,
		arg.ProjectID,
		arg.Branch,
		arg.CommitSha,
		arg.CiBuildID,
		arg.CiJobUrl,
		arg.MrIid,
	)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Branch,
		&i.CommitSha,
		&i.CiBuildID,
		&i.CiJobUrl,
		&i.MrIid,
		&i.Status,
		&i.CreatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const getBuild = `-- name: GetBuild :one
SELECT id, project_id, branch, commit_sha, ci_build_id, ci_job_url, mr_iid, status, created_at, finalized_at FROM builds WHERE id = $1
`

func (q *Queries) GetBuild(ctx context.Context, id string) (Build, error) {
	row := q.db.QueryRow(ctx, getBuild, id)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Branch,
		&i.CommitSha,
		&i.CiBuildID,
		&i.CiJobUrl,
		&i.MrIid,
		&i.Status,
		&i.CreatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const getBuildForUpdate = `-- name: GetBuildForUpdate :one
SELECT id, project_id, branch, commit_sha, ci_build_id, ci_job_url, mr_iid, status, created_at, finalized_at FROM builds WHERE id = $1 FOR UPDATE
`

// Serialize concurrent finalize/recompute on a build (rulebook §8.3).
func (q *Queries) GetBuildForUpdate(ctx context.Context, id string) (Build, error) {
	row := q.db.QueryRow(ctx, getBuildForUpdate, id)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Branch,
		&i.CommitSha,
		&i.CiBuildID,
		&i.CiJobUrl,
		&i.MrIid,
		&i.Status,
		&i.CreatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const imageExists = `-- name: ImageExists :one
SELECT EXISTS (SELECT 1 FROM images WHERE sha256 = $1) AS exists
`

func (q *Queries) ImageExists(ctx context.Context, sha256 string) (bool, error) {
	row := q.db.QueryRow(ctx, imageExists, sha256)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertRemovedSnapshot = `-- name: InsertRemovedSnapshot :exec
INSERT INTO snapshots (id, build_id, name, browser, viewport, baseline_id, status)
VALUES ($1, $2, $3, $4, $5, $6, 'REMOVED')
ON CONFLICT (build_id, name, browser, viewport) DO NOTHING
`

type InsertRemovedSnapshotParams struct {
	ID         string  `json:"id"`
	BuildID    string  `json:"build_id"`
	Name       string  `json:"name"`
	Browser    string  `json:"browser"`
	Viewport   string  `json:"viewport"`
	BaselineID *string `json:"baseline_id"`
}

func (q *Queries) InsertRemovedSnapshot(ctx context.Context, arg InsertRemovedSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertRemovedSnapshot,
		arg.ID,
		arg.BuildID,
		arg.Name,
		arg.Browser,
		arg.Viewport,
		arg.BaselineID,
	)
	return err
}

const listMissingBaselines = `-- name: ListMissingBaselines :many
SELECT b.id, b.name, b.browser, b.viewport
FROM baselines b
WHERE b.project_id = $1 AND b.branch = $2
  AND NOT EXISTS (
    SELECT 1 FROM snapshots s
    WHERE s.build_id = $3
      AND s.name = b.name AND s.browser = b.browser AND s.viewport = b.viewport
  )
`

type ListMissingBaselinesParams struct {
	ProjectID string `json:"project_id"`
	Branch    string `json:"branch"`
	BuildID   string `json:"build_id"`
}

type ListMissingBaselinesRow struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Browser  string `json:"browser"`
	Viewport string `json:"viewport"`
}

// REMOVED detection: baselines of (project, branch) with no matching snapshot in this build.
func (q *Queries) ListMissingBaselines(ctx context.Context, arg ListMissingBaselinesParams) ([]ListMissingBaselinesRow, error) {
	rows, err := q.db.Query(ctx, listMissingBaselines, arg.ProjectID, arg.Branch, arg.BuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMissingBaselinesRow
	for rows.Next() {
		var i ListMissingBaselinesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Browser,
			&i.Viewport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSnapshotIDs = `-- name: ListPendingSnapshotIDs :many
SELECT id FROM snapshots WHERE build_id = $1 AND status = 'PENDING'
`

// Snapshots that still need a diff comparison (enqueued on finalize).
func (q *Queries) ListPendingSnapshotIDs(ctx context.Context, buildID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listPendingSnapshotIDs, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBuildComparing = `-- name: SetBuildComparing :exec
UPDATE builds SET status = 'COMPARING', finalized_at = now() WHERE id = $1
`

func (q *Queries) SetBuildComparing(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setBuildComparing, id)
	return err
}

const upsertImage = `-- name: UpsertImage :exec
INSERT INTO images (sha256, width, height, byte_size)
VALUES ($1, $2, $3, $4)
ON CONFLICT (sha256) DO NOTHING
`

type UpsertImageParams struct {
	Sha256   string `json:"sha256"`
	Width    int32  `json:"width"`
	Height   int32  `json:"height"`
	ByteSize int32  `json:"byte_size"`
}

// Image metadata is content-addressed; the blob bytes live in object storage. ON CONFLICT DO NOTHING
// makes repeated declarations idempotent (the FK target for snapshots.new_image_sha).
func (q *Queries) UpsertImage(ctx context.Context, arg UpsertImageParams) error {
	_, err := q.db.Exec(ctx, upsertImage,
		arg.Sha256,
		arg.Width,
		arg.Height,
		arg.ByteSize,
	)
	return err
}

const upsertSnapshot = `-- name: UpsertSnapshot :one
INSERT INTO snapshots (id, build_id, name, browser, viewport, new_image_sha, status)
VALUES ($1, $2, $3, $4, $5, $6, 'PENDING')
ON CONFLICT (build_id, name, browser, viewport)
DO UPDATE SET new_image_sha = EXCLUDED.new_image_sha, status = 'PENDING'
RETURNING id, build_id, name, browser, viewport, new_image_sha, diff_image_sha, baseline_id, diff_ratio, diff_pixels, status, error_msg, created_at
`

type UpsertSnapshotParams struct {
	ID          string  `json:"id"`
	BuildID     string  `json:"build_id"`
	Name        string  `json:"name"`
	Browser     string  `json:"browser"`
	Viewport    string  `json:"viewport"`
	NewImageSha *string `json:"new_image_sha"`
}

// Idempotent snapshot declare (CI-retry safe) on the composite identity key.
func (q *Queries) UpsertSnapshot(ctx context.Context, arg UpsertSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRow(ctx, upsertSnapshot,
		arg.ID,
		arg.BuildID,
		arg.Name,
		arg.Browser,
		arg.Viewport,
		arg.NewImageSha,
	)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.BuildID,
		&i.Name,
		&i.Browser,
		&i.Viewport,
		&i.NewImageSha,
		&i.DiffImageSha,
		&i.BaselineID,
		&i.DiffRatio,
		&i.DiffPixels,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
	)
	return i, err
}
