// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApprovalAction string

const (
	ApprovalActionAPPROVE ApprovalAction = "APPROVE"
	ApprovalActionREJECT  ApprovalAction = "REJECT"
)

func (e *ApprovalAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApprovalAction(s)
	case string:
		*e = ApprovalAction(s)
	default:
		return fmt.Errorf("unsupported scan type for ApprovalAction: %T", src)
	}
	return nil
}

type NullApprovalAction struct {
	ApprovalAction ApprovalAction `json:"approval_action"`
	Valid          bool           `json:"valid"` // Valid is true if ApprovalAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApprovalAction) Scan(value interface{}) error {
	if value == nil {
		ns.ApprovalAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApprovalAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApprovalAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApprovalAction), nil
}

func (e ApprovalAction) Valid() bool {
	switch e {
	case ApprovalActionAPPROVE,
		ApprovalActionREJECT:
		return true
	}
	return false
}

func AllApprovalActionValues() []ApprovalAction {
	return []ApprovalAction{
		ApprovalActionAPPROVE,
		ApprovalActionREJECT,
	}
}

type BuildStatus string

const (
	BuildStatusRUNNING        BuildStatus = "RUNNING"
	BuildStatusCOMPARING      BuildStatus = "COMPARING"
	BuildStatusPASSED         BuildStatus = "PASSED"
	BuildStatusREVIEWREQUIRED BuildStatus = "REVIEW_REQUIRED"
	BuildStatusREJECTED       BuildStatus = "REJECTED"
	BuildStatusERROR          BuildStatus = "ERROR"
)

func (e *BuildStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BuildStatus(s)
	case string:
		*e = BuildStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BuildStatus: %T", src)
	}
	return nil
}

type NullBuildStatus struct {
	BuildStatus BuildStatus `json:"build_status"`
	Valid       bool        `json:"valid"` // Valid is true if BuildStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBuildStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BuildStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BuildStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBuildStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BuildStatus), nil
}

func (e BuildStatus) Valid() bool {
	switch e {
	case BuildStatusRUNNING,
		BuildStatusCOMPARING,
		BuildStatusPASSED,
		BuildStatusREVIEWREQUIRED,
		BuildStatusREJECTED,
		BuildStatusERROR:
		return true
	}
	return false
}

func AllBuildStatusValues() []BuildStatus {
	return []BuildStatus{
		BuildStatusRUNNING,
		BuildStatusCOMPARING,
		BuildStatusPASSED,
		BuildStatusREVIEWREQUIRED,
		BuildStatusREJECTED,
		BuildStatusERROR,
	}
}

type Role string

const (
	RoleOWNER  Role = "OWNER"
	RoleMEMBER Role = "MEMBER"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

func (e Role) Valid() bool {
	switch e {
	case RoleOWNER,
		RoleMEMBER:
		return true
	}
	return false
}

func AllRoleValues() []Role {
	return []Role{
		RoleOWNER,
		RoleMEMBER,
	}
}

type SnapshotStatus string

const (
	SnapshotStatusPENDING   SnapshotStatus = "PENDING"
	SnapshotStatusUNCHANGED SnapshotStatus = "UNCHANGED"
	SnapshotStatusCHANGED   SnapshotStatus = "CHANGED"
	SnapshotStatusNEW       SnapshotStatus = "NEW"
	SnapshotStatusREMOVED   SnapshotStatus = "REMOVED"
	SnapshotStatusAPPROVED  SnapshotStatus = "APPROVED"
	SnapshotStatusREJECTED  SnapshotStatus = "REJECTED"
	SnapshotStatusERROR     SnapshotStatus = "ERROR"
)

func (e *SnapshotStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SnapshotStatus(s)
	case string:
		*e = SnapshotStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SnapshotStatus: %T", src)
	}
	return nil
}

type NullSnapshotStatus struct {
	SnapshotStatus SnapshotStatus `json:"snapshot_status"`
	Valid          bool           `json:"valid"` // Valid is true if SnapshotStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSnapshotStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SnapshotStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SnapshotStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSnapshotStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SnapshotStatus), nil
}

func (e SnapshotStatus) Valid() bool {
	switch e {
	case SnapshotStatusPENDING,
		SnapshotStatusUNCHANGED,
		SnapshotStatusCHANGED,
		SnapshotStatusNEW,
		SnapshotStatusREMOVED,
		SnapshotStatusAPPROVED,
		SnapshotStatusREJECTED,
		SnapshotStatusERROR:
		return true
	}
	return false
}

func AllSnapshotStatusValues() []SnapshotStatus {
	return []SnapshotStatus{
		SnapshotStatusPENDING,
		SnapshotStatusUNCHANGED,
		SnapshotStatusCHANGED,
		SnapshotStatusNEW,
		SnapshotStatusREMOVED,
		SnapshotStatusAPPROVED,
		SnapshotStatusREJECTED,
		SnapshotStatusERROR,
	}
}

type ApiKey struct {
	ID         string             `json:"id"`
	ProjectID  string             `json:"project_id"`
	KeyHash    string             `json:"key_hash"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type ApprovalEvent struct {
	ID         string             `json:"id"`
	SnapshotID string             `json:"snapshot_id"`
	UserID     string             `json:"user_id"`
	Action     ApprovalAction     `json:"action"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Baseline struct {
	ID                string             `json:"id"`
	ProjectID         string             `json:"project_id"`
	Branch            string             `json:"branch"`
	Name              string             `json:"name"`
	Browser           string             `json:"browser"`
	Viewport          string             `json:"viewport"`
	ImageSha          string             `json:"image_sha"`
	ApprovedByUserID  *string            `json:"approved_by_user_id"`
	ApprovedInBuildID *string            `json:"approved_in_build_id"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Build struct {
	ID          string             `json:"id"`
	ProjectID   string             `json:"project_id"`
	Branch      string             `json:"branch"`
	CommitSha   string             `json:"commit_sha"`
	CiBuildID   *string            `json:"ci_build_id"`
	CiJobUrl    *string            `json:"ci_job_url"`
	MrIid       *string            `json:"mr_iid"`
	Status      BuildStatus        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	FinalizedAt pgtype.Timestamptz `json:"finalized_at"`
}

type Image struct {
	Sha256    string             `json:"sha256"`
	Width     int32              `json:"width"`
	Height    int32              `json:"height"`
	ByteSize  int32              `json:"byte_size"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Membership struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
	Role      Role   `json:"role"`
}

type Project struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	DefaultBranch   string             `json:"default_branch"`
	GitlabProjectID *string            `json:"gitlab_project_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Snapshot struct {
	ID           string             `json:"id"`
	BuildID      string             `json:"build_id"`
	Name         string             `json:"name"`
	Browser      string             `json:"browser"`
	Viewport     string             `json:"viewport"`
	NewImageSha  *string            `json:"new_image_sha"`
	DiffImageSha *string            `json:"diff_image_sha"`
	BaselineID   *string            `json:"baseline_id"`
	DiffRatio    *float64           `json:"diff_ratio"`
	DiffPixels   *int32             `json:"diff_pixels"`
	Status       SnapshotStatus     `json:"status"`
	ErrorMsg     *string            `json:"error_msg"`
	BaselinePath *string            `json:"baseline_path"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	Name         *string            `json:"name"`
	PasswordHash *string            `json:"password_hash"`
	GitlabID     *string            `json:"gitlab_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
